### ISSUE TITLE
Date on info popup seems to be broken

### ISSUE THREAD

**Issue by braddf** [openclimatefix/quartz-frontend#353]
## Describe the bug
Showing `Invalid Date` instead of the formatted datestamp; most likely from one of my changes of data source objects to simplify the FE API calls and data use.

## To Reproduce
1. Go to [Staging](https://staging.nowcasting.io)
2. Hover over the (i) in the chart legend or in the profile dropdown in the top right of the screen
3. Date at bottom displaying incorrectly

## Expected behavior
Should should the formatted datestamp, as before.

## Additional context
Hopefully is just a mismatch in the input format or similar from the forecast data as it goes into the formatting function.

**Comment by peterdudfield** [comment]
@brad if you let me know which data this is showing, I could check in the API that this is being made correctly

**Comment by peterdudfield** [comment]
Did this get solved? I found sometimes you had to wait until the GSP is loaded, then its fine
