### ISSUE TITLE
change email address on app site

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/quartz-frontend#406]
The email address on the contact OCF is currently ops@....

This is out of date, as ops is now the internal operations.  Change to current appropriate service support group.

**Comment by peterdudfield** [comment]
What email is this?

**Comment by peterdudfield** [comment]
@dantravers whats the email address this should be directed too, I would suggest something like support@openclimatefix.org

**Comment by peterdudfield** [comment]
Lets go for [quartz.support@openclimatefix.org](mailto:quartz.support@openclimatefix.org)
