### ISSUE TITLE
chartings - zoom 

### ISSUE THREAD

**Issue by rachel-labri-tipton** [openclimatefix/quartz-frontend#409]
## Detailed Description
Investigate if it's possible to add an option to zoom in on the national, gsp, and pv site forecast charts. 

## Context
This is a feature we have on the `OCF Dashboard` thanks to the plotly library and it's  possible to click on a chart and you are able to zoom in and get a bit more granularity on the chart. 

## Possible Implementation

- [ ] Investigate Rechart’s functionality: [recharts library](https://recharts.org/en-US/examples/HighlightAndZoomLineChart) 
- [ ] Investigate a different package
- [ ] Talk to users

**Comment by rachel-labri-tipton** [comment]
Another option: [plotly js](https://plotly.com/javascript/)

**Comment by peterdudfield** [comment]
There is a feature in the current library, next job to try this out
