### ISSUE TITLE
Mobile optimisation of site UI

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/quartz-frontend#425]
It isn't possible to use the app on a phone today for sites. 

Next step is to determine the users more to see more if what we have is enough or what we need to invest.

**Comment by peterdudfield** [comment]
Just to double check, is this for the quartz.solar app?

**Comment by dantravers** [comment]
yep

**Comment by peterdudfield** [comment]
I've put it into UI/UX so we can prioritise as we need to

**Comment by peterdudfield** [comment]
Currently looks funny on my Samsun s9
