### ISSUE TITLE
Size of yellow blobs

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/quartz-frontend#437]
Current the yellow blobs for size don't quite seem right.

I think letting the radius be r = {yield}^0.5. this means Area is proportional the yield.

**Comment by braddf** [comment]
Dan via Vercel Preview:

> The "visual weight" of the coloured in circles should be greater.  I'm not sure of the pixel count, but maybe it feels like if I look at a GSP with 20% yield, the yellow ball looks like way less than 20%.  
>Options could be:  
>a) when working our the radius the yellow ball should be, calcualte the generation as a % of 80% of the max capacity.  This is becasue solar panels never get to full capacity, so we would be safe with 80%. 
>b) work out the radius of the yellow ball such that the square of the radius is equal to the fraction of the square of the capacity (I.e. a ratio of areas, whcih will make the radius of the smaller dot larger compared to a simple linear method).

**Comment by peterdudfield** [comment]
a) My panels do reach 100%, so IM not sure this is the best option
b) yea I like this. similar what I said above
