### ISSUE TITLE
Small aesthetic changes to Download CSV

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/quartz-frontend#491]
Very minor issue to tidy up the download csv: 
solarGenerationData | windGenerationData | solarForecastData | windForecastData

Change to 
Solar_generation; Wind_generation; Solar_forecast; Wind_forecast
or similar if you want to tweak. 

Can we change the file name to be: Quartz_data.csv
If it's possible to introduce a date-time to the file name, that it useful, as if you download a lot of files it gets very confusing (from personal experience!)
E.g. Quartz_data_2024-03-08_1403.csv

**Comment by aryanbhosale** [comment]
Hi @braddf , i see that you've self-assigned this issue, but if you don't mind, can i get my hands dirty on this?
Thank you

**Comment by aryanbhosale** [comment]
> Hey @aryanbhosale, welcome to the repo! 
> 
> Sorry, bit of bad housekeeping on my part on this one and it's already done – have had a bit of a tidy up and marked some issues with the `good first issue` tag if you want to check any of those out. 
> 
> NB: if/when you do make any Pull Requests – I can see you've had a grand tour of a few of our repos, so thanks for that – but do **make sure you fill in the PR descriptions as best you can** to help out reviewers, otherwise we may not have time to work out what is being fixed, how and why.
> 
> Hoping to get some time soon to overhaul the data handling/auth on this repo to make it much easier for folks to dip in and help out on the frontend apps, so watch this space for some more interesting tasks soon!

Hi @braddf ,thanks for the update, and yeah I will make sure to make the PRs as descriptive as I can in my future work here. Ill keep an eye on the other tasks. 
Thanks again:)
