### ISSUE TITLE
Delta map not showing

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/quartz-frontend#500]
![Screenshot 2024-03-27 at 15 43 35](https://github.com/openclimatefix/quartz-frontend/assets/34686298/3e08d673-7e9a-4828-98b6-a304438ec3b1)

**Comment by peterdudfield** [comment]
You ok to put is as done in the OCF project too?

**Comment by braddf** [comment]
Is now `On Staging` then will go through all the `Done`s after this release 👌
