### ISSUE TITLE
Add Auto welcome email

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/quartz-frontend#506]
It looks like we can send a custom email but we need to set up email provider first on Auth0

![Image](https://github.com/openclimatefix/quartz-frontend/assets/34686298/dce1c226-41a1-4bdc-89c0-4623a30f0979)

**Comment by peterdudfield** [comment]
@braddf 
![Image](https://github.com/openclimatefix/quartz-frontend/assets/34686298/280338c6-f161-420e-848e-bd03c5124219)

you ever set up any of these before?

**Comment by braddf** [comment]
@peterdudfield yep I have used Sendgrid, Mailgun and Mandrill before – much over muchness I think they were all fairly easy to set up/integrate

**Comment by peterdudfield** [comment]
Ill put the feedback in here
- 
<img width="382" alt="Screenshot 2024-05-03 at 10 13 24" src="https://github.com/openclimatefix/quartz-frontend/assets/34686298/c907a41b-c83f-4c68-a0d9-5f3672b1110b">
This is a little bit raw, so could be made a page
- Could also add an email address to contact OCF with in this message. quartz.support@openclimatefix.org
