### ISSUE TITLE
Quartz Solar – Sites view charts responsive/squished when table too long

### ISSUE THREAD

**Issue by braddf** [openclimatefix/quartz-frontend#541]
## Describe the bug
Open Quartz Solar and head to Sites view

## To Reproduce
1. Select DNO aggregation if not already
2. Should squish the aggregated chart
3. Selecting a DNO should show 2 squished charts

## Expected behavior
Non-squished charts

**Comment by peterdudfield** [comment]
@braddf did this get fixed?

**Comment by dantravers** [comment]
I get a double scroll bar when look at it on staging: 
![image](https://github.com/user-attachments/assets/e77724b6-9b97-4262-8d01-134f0fc61b88)
